### PR TITLE
Remove init requirement & syntax sugar from Withable

### LINKED ISSUE #49: Withable not working on custom types with init parameters
## Expected Behavior
When I have a `Task` type like so:
```swift
class Task: Withable {
    var name: String
    var absolutePriority: UInt64? = nil
}
```

I should be able to write code like this:

```swift
let tasks: [Task] = [
    SingleTask(name: "Task1").with { $0.absolutePriority = -100 },
    SingleTask(name: "Task2").with { $0.absolutePriority = -50 },
    SingleTask(name: "Task3").with { $0.absolutePriority = 0 },
    SingleTask(name: "Task4").with { $0.absolutePriority = 25 },
    SingleTask(name: "Task5").with { $0.absolutePriority = 50 },
]
```

## Actual Behavior
It's not building because `Withable` requires my type not not have any parameters in the `init` method, which shouldn't be the case.

## Steps to Reproduce the Problem
See code above. 

## Specifications

  - Version: 3.2.0
  - Platform: macOS 10.15.4
  - IDE Version: Xcode 11.5

### PR DESCRIPTION
**Pull request by Jeehut**
Fixes #49.

## Proposed Changes

  - Remove the `init()` requirement from `Withable`.
  - Remove the `init` syntax sugar method that allowed `Foo { $0.bar = 5}` in favor of `Foo().with { $0.bar = 5}`.
  - Adds support for `Foo(bar: 5).with { $0.otherProperty = true }` without requiring `init()` on `Foo` type.

### CODE REVIEW

**Comment by Jeehut** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 50
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214&bid=18745993)

File: lint.swift [hunk 1]
```diff
@@ -0,0 +1,547 @@
...
+            "callPart3": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
+        ],
+        matchingExamples: ["call(x: (viewModel?.profile?.username)!)"],
+        nonMatchingExamples: ["let x = (viewModel?.user?.profile?.imagePath)!\n", "let x = viewModel!.profile!.imagePath\n"],
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: "$callPart1!.$callPart2!.$callPart3",
+        autoCorrectExamples: [
+            ["before": "let x = (viewModel?.profile?.imagePath)!\n", "after": "let x = viewModel!.profile!.imagePath\n"]
```
Comment (Jeehut) [inline lint.swift:160]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 2]
```diff
@@ -0,0 +1,547 @@
...
+import AnyLint // @Flinesoft ~> 0.8.2
+
+try Lint.logSummaryAndExit(arguments: CommandLine.arguments) {
+	// MARK: - Variables
+	let swiftFiles: Regex = #"^Sources/.*\.swift$"#
+	let testFiles: Regex = #"^Tests/.*\.swift$"#
+  let readmeFile: Regex = #"README\.md"#
+  let changelogFile: Regex = #"^CHANGELOG\.md$"#
+
+	// MARK: - Checks
```
Comment (Jeehut) [inline lint.swift:11]: Codacy found an issue: [Include a single vertical whitespace (empty line) before and none after MARK: comments.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 3]
```diff
@@ -0,0 +1,547 @@
...
+            [
+                "before": "param: callFunction(errorMessage != nil ? errorMessage! : L10n.Global.Info.success),\n",
+                "after": "param: callFunction(errorMessage ?? L10n.Global.Info.success),\n"
+            ]
+        ]
+    )
+
+    // MARK: SingleLineGuard
+    try Lint.checkFileContents(
+        checkInfo: "SingleLineGuard: Use a single line guard for simple checks.",
```
Comment (Jeehut) [inline lint.swift:349]: Codacy found an issue: [Always close a multiline guard via `else {` on a new line indented like the opening `guard`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 1 above)
Comment (Jeehut) [inline lint.swift:160]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 4]
```diff
@@ -0,0 +1,547 @@
...
+            ["before": "func foo2bar(\n    x: Int,\n    y: Int\n) {\n    \n}", "after": "func foo2bar(\n    x: Int,\n    y: Int\n) {}"]
+        ]
+    )
+
+    // MARK: EmptyTodo
+    try Lint.checkFileContents(
+        checkInfo: "EmptyTodo: `// TODO:` comments should not be empty.",
+        regex: #"// TODO: ?(\[[\d\-_a-z]+\])? *\n"#,
+        matchingExamples: ["// TODO:\n", "// TODO: [2020-03-19]\n", "// TODO: [cg_2020-03-19]  \n"],
+        nonMatchingExamples: ["// TODO: refactor", "// TODO: not yet implemented", "// TODO: [cg_2020-03-19] not yet implemented"],
```
Comment (Jeehut) [inline lint.swift:103]: Codacy found an issue: [Use a '// REFACTOR:' comment instead.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 5]
```diff
@@ -0,0 +1,547 @@
...
+            ["before": "\n- Fixed a bug.\n Issue: [Link](#)", "after": "\n- Fixed a bug.\n  Issue: [Link](#)"],
+            ["before": "\n- Fixed a bug.\n    Issue: [Link](#)", "after": "\n- Fixed a bug.\n  Issue: [Link](#)"],
+        ]
+    )
+
+    // MARK: ClosureParamsParantheses
+    try Lint.checkFileContents(
+        checkInfo: "ClosureParamsParantheses: Don't use parantheses around non-typed parameters in a closure.",
+        regex: #"\{\s*\(((?!self)[^):]+)\)\s*in"#,
+        matchingExamples: ["run { (a) in", "run { (a, b) in", "run { (a, b, c) in"],
```
Comment (Jeehut) [inline lint.swift:58]: Codacy found an issue: [Don't use parantheses around non-typed parameters in a closure.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 6]
```diff
@@ -0,0 +1,547 @@
...
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: "$declaration {}",
+        autoCorrectExamples: [
+            ["before": "init()  { }", "after": "init() {}"],
+            ["before": "init(x: Int, y: Int)  { }", "after": "init(x: Int, y: Int) {}"],
+            ["before": "init()\n{\n    \n}", "after": "init() {}"],
+            ["before": "init(\n    x: Int,\n    y: Int\n) {\n    \n}", "after": "init(\n    x: Int,\n    y: Int\n) {}"],
+            ["before": "func foo2bar()  { }", "after": "func foo2bar() {}"],
+            ["before": "func foo2bar(x: Int, y: Int)  { }", "after": "func foo2bar(x: Int, y: Int) {}"],
+            ["before": "func foo2bar()\n{\n    \n}", "after": "func foo2bar() {}"],
```
Comment (Jeehut) [inline lint.swift:93]: Codacy found an issue: [Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 7]
```diff
@@ -0,0 +1,547 @@
...
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: "$declaration {}",
+        autoCorrectExamples: [
+            ["before": "init()  { }", "after": "init() {}"],
+            ["before": "init(x: Int, y: Int)  { }", "after": "init(x: Int, y: Int) {}"],
+            ["before": "init()\n{\n    \n}", "after": "init() {}"],
+            ["before": "init(\n    x: Int,\n    y: Int\n) {\n    \n}", "after": "init(\n    x: Int,\n    y: Int\n) {}"],
+            ["before": "func foo2bar()  { }", "after": "func foo2bar() {}"],
+            ["before": "func foo2bar(x: Int, y: Int)  { }", "after": "func foo2bar(x: Int, y: Int) {}"],
```
Comment (Jeehut) [inline lint.swift:92]: Codacy found an issue: [Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 8]
```diff
@@ -0,0 +1,547 @@
...
+        ],
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles]
+    )
+
+    // MARK: NavigationControllerVariableNaming
+    try Lint.checkFileContents(
+        checkInfo: "NavigationControllerVariableNaming: Always name your navigation controller variables with the suffix `NavCtrl` or just `navCtrl`.",
+        regex: #"(var|let) +(nc|navigationcontroller|navc|ncontroller|navcontroller)[ :][^\n=]*=\i"#,
+        matchingExamples: ["let nc =", "var navigationController =", "let navc =", "let ncontroller =", "var nc: MyNavigationController =", "let navController: MyNavigationController<T> = "],
```
Comment (Jeehut) [inline lint.swift:312]: Codacy found an issue: [Always name your view controller variables with the suffix `ViewCtrl`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 3 above)
Comment (Jeehut) [inline lint.swift:349]: Codacy found an issue: [Always start a multiline guard via `guard` then a line break and all expressions indented.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 9]
```diff
@@ -0,0 +1,547 @@
...
+            ["before": "func foo2bar()\n{\n    \n}", "after": "func foo2bar() {}"],
+            ["before": "func foo2bar(\n    x: Int,\n    y: Int\n) {\n    \n}", "after": "func foo2bar(\n    x: Int,\n    y: Int\n) {}"]
+        ]
+    )
+
+    // MARK: EmptyTodo
+    try Lint.checkFileContents(
+        checkInfo: "EmptyTodo: `// TODO:` comments should not be empty.",
+        regex: #"// TODO: ?(\[[\d\-_a-z]+\])? *\n"#,
+        matchingExamples: ["// TODO:\n", "// TODO: [2020-03-19]\n", "// TODO: [cg_2020-03-19]  \n"],
```
Comment (Jeehut) [inline lint.swift:102]: Codacy found an issue: [All TODOs should exactly start like this (mind the whitespacing): `// TODO: [cg_YYYY-MM-DD] `.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 10]
```diff
@@ -0,0 +1,547 @@
...
+            "callPart1": #"[^\s\?\.]+"#,
+            "separator1": #"\?\."#,
+            "callPart2": #"[^\s\?\.]+"#,
+            "separator2": #"\?\."#,
+            "callPart3": #"[^\s\?\.]+"#,
+            "separator3": #"\?\."#,
+            "callPart4": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
+        ],
+        matchingExamples: ["let x = (viewModel?.user?.profile?.imagePath)!\n"],
```
Comment (Jeehut) [inline lint.swift:132]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 11]
```diff
@@ -0,0 +1,547 @@
...
+            "callPart2": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
+        ],
+        matchingExamples: ["call(x: (viewModel?.username)!)"],
+        nonMatchingExamples: ["call(x: (viewModel?.profile?.username)!)", "call(x: viewModel!.username)"],
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: "$callPart1!.$callPart2",
+        autoCorrectExamples: [
+            ["before": "call(x: (viewModel?.username)!)", "after": "call(x: viewModel!.username)"]
```
Comment (Jeehut) [inline lint.swift:180]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 12]
```diff
@@ -0,0 +1,547 @@
...
+        autoCorrectReplacement: "$declaration {}",
+        autoCorrectExamples: [
+            ["before": "init()  { }", "after": "init() {}"],
+            ["before": "init(x: Int, y: Int)  { }", "after": "init(x: Int, y: Int) {}"],
+            ["before": "init()\n{\n    \n}", "after": "init() {}"],
+            ["before": "init(\n    x: Int,\n    y: Int\n) {\n    \n}", "after": "init(\n    x: Int,\n    y: Int\n) {}"],
+            ["before": "func foo2bar()  { }", "after": "func foo2bar() {}"],
+            ["before": "func foo2bar(x: Int, y: Int)  { }", "after": "func foo2bar(x: Int, y: Int) {}"],
+            ["before": "func foo2bar()\n{\n    \n}", "after": "func foo2bar() {}"],
+            ["before": "func foo2bar(\n    x: Int,\n    y: Int\n) {\n    \n}", "after": "func foo2bar(\n    x: Int,\n    y: Int\n) {}"]
```
Comment (Jeehut) [inline lint.swift:94]: Codacy found an issue: [Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 13]
```diff
@@ -0,0 +1,547 @@
...
+    try Lint.checkFileContents(
+        checkInfo: "LateForceUnwrapping1: Don't use ? first to force unwrap later – directly unwrap within the parantheses.",
+        regex: [
+            "openingBrace": #"\("#,
+            "callPart1": #"[^\s\?\.]+"#,
+            "separator1": #"\?\."#,
+            "callPart2": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
+        ],
+        matchingExamples: ["call(x: (viewModel?.username)!)"],
```
Comment (Jeehut) [inline lint.swift:174]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 14]
```diff
@@ -0,0 +1,547 @@
...
+        regex: [
+            "openingBrace": #"\("#,
+            "callPart1": #"[^\s\?\.]+"#,
+            "separator1": #"\?\."#,
+            "callPart2": #"[^\s\?\.]+"#,
+            "separator2": #"\?\."#,
+            "callPart3": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
+        ],
+        matchingExamples: ["call(x: (viewModel?.profile?.username)!)"],
```
Comment (Jeehut) [inline lint.swift:154]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 15]
```diff
@@ -0,0 +1,547 @@
...
+    try Lint.checkFileContents(
+        checkInfo: "EmptyMethodBody: Don't use whitespace or newlines for the body of empty methods.",
+        regex: ["declaration": #"(init|func [^\(\s]+)\([^{}]*\)"#, "spacing": #"\s*"#, "body": #"\{\s+\}"#],
+        matchingExamples: [
+            "init() { }",
+            "init() {\n\n}",
+            "init(\n    x: Int,\n    y: Int\n) { }",
+            "func foo2bar()  { }",
+            "func foo2bar(x: Int, y: Int)  { }",
+            "func foo2bar(\n    x: Int,\n    y: Int\n) {\n    \n}"
```
Comment (Jeehut) [inline lint.swift:80]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 12 above)
Comment (Jeehut) [inline lint.swift:94]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 16]
```diff
@@ -0,0 +1,547 @@
...
+        matchingExamples: [
+            """
+            guard
+                let collection = viewModel.myCollection(),
+                !collection.compactMap({ OtherType($0) }).isEmpty() else {
+                return
+            }
+            """,
+            """
+            guard let collection = viewModel.myCollection(),
```
Comment (Jeehut) [inline lint.swift:241]: Codacy found an issue: [Always close a multiline guard via `else {` on a new line indented like the opening `guard`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 17]
```diff
@@ -0,0 +1,547 @@
...
+        regex: [
+            "openingBrace": #"\("#,
+            "callPart1": #"[^\s\?\.]+"#,
+            "separator1": #"\?\."#,
+            "callPart2": #"[^\s\?\.]+"#,
+            "separator2": #"\?\."#,
+            "callPart3": #"[^\s\?\.]+"#,
+            "separator3": #"\?\."#,
+            "callPart4": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
```
Comment (Jeehut) [inline lint.swift:130]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 18]
```diff
@@ -0,0 +1,547 @@
...
+    try Lint.checkFileContents(
+        checkInfo: "NilCoalescingOperator: Prefer nil coalescing operator over `variable != nil ? variable! : alternative`.",
+        regex: #"(\w+)\s*!=\s*nil\s*\?\s*\1!\s*:\s*(.*)"#,
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: "$1 ?? $2",
+        autoCorrectExamples: [
+            [
+                "before": "    let message = errorMessage != nil ? errorMessage! : L10n.Global.Info.success\n",
+                "after": "    let message = errorMessage ?? L10n.Global.Info.success\n"
```
Comment (Jeehut) [inline lint.swift:338]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 11 above)
Comment (Jeehut) [inline lint.swift:180]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 19]
```diff
@@ -0,0 +1,547 @@
...
+                        dataExporterHelper.exportData(
+                """,
+                "after": """
+                    if
+                        let employee = UserDefaults.standard.currentEmployee(),
+                        let recipientEmail = recipientEmail
+                    {
+                        dataExporterHelper.exportData(
+                """
+            ]
```
Comment (Jeehut) [inline lint.swift:224]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 20]
```diff
@@ -0,0 +1,547 @@
...
+        regex: ["declaration": #"(init|func [^\(\s]+)\([^{}]*\)"#, "spacing": #"\s*"#, "body": #"\{\s+\}"#],
+        matchingExamples: [
+            "init() { }",
+            "init() {\n\n}",
+            "init(\n    x: Int,\n    y: Int\n) { }",
+            "func foo2bar()  { }",
+            "func foo2bar(x: Int, y: Int)  { }",
+            "func foo2bar(\n    x: Int,\n    y: Int\n) {\n    \n}"
+        ],
+        nonMatchingExamples: ["init() { /* comment */ }", "init() {}", "func foo2bar() {}", "func foo2bar(x: Int, y: Int) {}"],
```
Comment (Jeehut) [inline lint.swift:82]: Codacy found an issue: [Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 21]
```diff
@@ -0,0 +1,547 @@
...
+        regex: #"\{\s*\(((?!self)[^):]+)\)\s*in"#,
+        matchingExamples: ["run { (a) in", "run { (a, b) in", "run { (a, b, c) in"],
+        nonMatchingExamples: ["run { (a: Int) in", "run { (a: Int, b: Int) in", "run { (a, b) -> String in"],
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: #"{ $1 in"#,
+        autoCorrectExamples: [
+            ["before": "run { (a) in", "after": "run { a in"],
+            ["before": "run { (a, b) in", "after": "run { a, b in"],
+            ["before": "run { (a, b, c) in", "after": "run { a, b, c in"]
```
Comment (Jeehut) [inline lint.swift:66]: Codacy found an issue: [Don't use parantheses around non-typed parameters in a closure.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

**Comment by Jeehut** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 50
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214&bid=18745993)

File: lint.swift [hunk 22]
```diff
@@ -0,0 +1,547 @@
...
+    try Lint.checkFileContents(
+        checkInfo: "ClosureParamsParantheses: Don't use parantheses around non-typed parameters in a closure.",
+        regex: #"\{\s*\(((?!self)[^):]+)\)\s*in"#,
+        matchingExamples: ["run { (a) in", "run { (a, b) in", "run { (a, b, c) in"],
+        nonMatchingExamples: ["run { (a: Int) in", "run { (a: Int, b: Int) in", "run { (a, b) -> String in"],
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: #"{ $1 in"#,
+        autoCorrectExamples: [
+            ["before": "run { (a) in", "after": "run { a in"],
```
Comment (Jeehut) [inline lint.swift:64]: Codacy found an issue: [Don't use parantheses around non-typed parameters in a closure.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 21 above)
Comment (Jeehut) [inline lint.swift:66]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 1 above)
Comment (Jeehut) [inline lint.swift:160]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 23]
```diff
@@ -0,0 +1,547 @@
...
+            "callPart4": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
+        ],
+        matchingExamples: ["let x = (viewModel?.user?.profile?.imagePath)!\n"],
+        nonMatchingExamples: ["call(x: (viewModel?.username)!)", "let x = viewModel!.user!.profile!.imagePath\n"],
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: "$callPart1!.$callPart2!.$callPart3!.$callPart4",
+        autoCorrectExamples: [
+            ["before": "let x = (viewModel?.user?.profile?.imagePath)!\n", "after": "let x = viewModel!.user!.profile!.imagePath\n"]
```
Comment (Jeehut) [inline lint.swift:138]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 24]
```diff
@@ -0,0 +1,547 @@
...
+            ["before": "func foo2bar(x: Int, y: Int)  { }", "after": "func foo2bar(x: Int, y: Int) {}"],
+            ["before": "func foo2bar()\n{\n    \n}", "after": "func foo2bar() {}"],
+            ["before": "func foo2bar(\n    x: Int,\n    y: Int\n) {\n    \n}", "after": "func foo2bar(\n    x: Int,\n    y: Int\n) {}"]
+        ]
+    )
+
+    // MARK: EmptyTodo
+    try Lint.checkFileContents(
+        checkInfo: "EmptyTodo: `// TODO:` comments should not be empty.",
+        regex: #"// TODO: ?(\[[\d\-_a-z]+\])? *\n"#,
```
Comment (Jeehut) [inline lint.swift:101]: Codacy found an issue: [All TODOs should have a format with creator credentials & date of their creation documented like this: `// TODO: [cg_YYYY-MM-DD] `.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 25]
```diff
@@ -0,0 +1,547 @@
...
+                "after": "param: callFunction(errorMessage ?? L10n.Global.Info.success),\n"
+            ]
+        ]
+    )
+
+    // MARK: SingleLineGuard
+    try Lint.checkFileContents(
+        checkInfo: "SingleLineGuard: Use a single line guard for simple checks.",
+        regex: #"guard\s*([^\{]{2,80})\s+else\s*\{\s*\n\s*(return[^\n]{0,40}|continue|fatalError\([^\n;]+\))\s*\}"#,
+        matchingExamples: ["guard x else {\n  return\n}", "guard x else {\n  return 2 * x.squared(x: {15})\n}", #"guard x else {\#n  fatalError("some message: \(x)")\#n}"#],
```
Comment (Jeehut) [inline lint.swift:351]: Codacy found an issue: [Line should be 160 characters or less: currently 173 characters](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 17 above)
Comment (Jeehut) [inline lint.swift:130]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 6 above)
Comment (Jeehut) [inline lint.swift:93]: Codacy found an issue: [Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 9 above)
Comment (Jeehut) [inline lint.swift:102]: Codacy found an issue: [All TODOs should have a format with creator credentials & date of their creation documented like this: `// TODO: [cg_YYYY-MM-DD] `.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 19 above)
Comment (Jeehut) [inline lint.swift:224]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 26]
```diff
@@ -0,0 +1,547 @@
+#!/usr/local/bin/swift-sh
+import AnyLint // @Flinesoft ~> 0.8.2
```
Comment (Jeehut) [inline lint.swift:2]: Codacy found an issue: [Header comments should be consistent with project patterns.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 27]
```diff
@@ -0,0 +1,547 @@
...
+            ]
+        ]
+    )
+
+    // MARK: SingleLineGuard
+    try Lint.checkFileContents(
+        checkInfo: "SingleLineGuard: Use a single line guard for simple checks.",
+        regex: #"guard\s*([^\{]{2,80})\s+else\s*\{\s*\n\s*(return[^\n]{0,40}|continue|fatalError\([^\n;]+\))\s*\}"#,
+        matchingExamples: ["guard x else {\n  return\n}", "guard x else {\n  return 2 * x.squared(x: {15})\n}", #"guard x else {\#n  fatalError("some message: \(x)")\#n}"#],
+        nonMatchingExamples: ["guard x else { return }", "guard x else { return 2 * x.squared(x: {15}) }", #"guard x else { fatalError("some message: \(x)") }"#],
```
Comment (Jeehut) [inline lint.swift:352]: Codacy found an issue: [Line should be 160 characters or less: currently 162 characters](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 28]
```diff
@@ -0,0 +1,547 @@
...
+        regex: #"// TODO: ?(\[[\d\-_a-z]+\])? *\n"#,
+        matchingExamples: ["// TODO:\n", "// TODO: [2020-03-19]\n", "// TODO: [cg_2020-03-19]  \n"],
+        nonMatchingExamples: ["// TODO: refactor", "// TODO: not yet implemented", "// TODO: [cg_2020-03-19] not yet implemented"],
+        includeFilters: [swiftFiles],
+        excludeFilters: [testFiles]
+    )
+
+    // MARK: IfAsGuard
+    try Lint.checkFileContents(
+        checkInfo: "IfAsGuard: Don't use an if statement to just return – use guard for such cases instead.",
```
Comment (Jeehut) [inline lint.swift:110]: Codacy found an issue: [Always start a multiline guard via `guard` then a line break and all expressions indented.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 11 above)
Comment (Jeehut) [inline lint.swift:180]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 16 above)
Comment (Jeehut) [inline lint.swift:241]: Codacy found an issue: [Always start a multiline guard via `guard` then a line break and all expressions indented.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 8 above)
Comment (Jeehut) [inline lint.swift:312]: Codacy found an issue: [Always name your view controller variables with the suffix `ViewCtrl`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 5 above)
Comment (Jeehut) [inline lint.swift:58]: Codacy found an issue: [Don't use parantheses around non-typed parameters in a closure.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 29]
```diff
@@ -0,0 +1,547 @@
...
+        ]
+    )
+
+    // MARK: MultilineGuardEnd
+    try Lint.checkFileContents(
+        checkInfo: "MultilineGuardEnd: Always close a multiline guard via `else {` on a new line indented like the opening `guard`.",
+        regex: #"guard\s*([^\n]*,\n)+([^\n]*\S *)else\s*\{"#,
+        matchingExamples: [
+            """
+            guard
```
Comment (Jeehut) [inline lint.swift:234]: Codacy found an issue: [Always close a multiline guard via `else {` on a new line indented like the opening `guard`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 11 above)
Comment (Jeehut) [inline lint.swift:180]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 14 above)
Comment (Jeehut) [inline lint.swift:154]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 30]
```diff
@@ -0,0 +1,547 @@
...
+        checkInfo: "LateForceUnwrapping1: Don't use ? first to force unwrap later – directly unwrap within the parantheses.",
+        regex: [
+            "openingBrace": #"\("#,
+            "callPart1": #"[^\s\?\.]+"#,
+            "separator1": #"\?\."#,
+            "callPart2": #"[^\s\?\.]+"#,
+            "closingBraceUnwrap": #"\)!"#
+        ],
+        matchingExamples: ["call(x: (viewModel?.username)!)"],
+        nonMatchingExamples: ["call(x: (viewModel?.profile?.username)!)", "call(x: viewModel!.username)"],
```
Comment (Jeehut) [inline lint.swift:175]: Codacy found an issue: [Don't use ? first to force unwrap later ? directly unwrap within the parantheses.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 7 above)
Comment (Jeehut) [inline lint.swift:92]: Codacy found an issue: [Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 4 above)
Comment (Jeehut) [inline lint.swift:103]: Codacy found an issue: [All TODOs should have a format with creator credentials & date of their creation documented like this: `// TODO: [cg_YYYY-MM-DD] `.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift (hunk 3 above)
Comment (Jeehut) [inline lint.swift:349]: Codacy found an issue: [Always start a multiline guard via `guard` then a line break and all expressions indented.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

File: lint.swift [hunk 31]
```diff
@@ -0,0 +1,547 @@
...
+        excludeFilters: [testFiles],
+        autoCorrectReplacement: "$1 ?? $2",
+        autoCorrectExamples: [
+            [
+                "before": "    let message = errorMessage != nil ? errorMessage! : L10n.Global.Info.success\n",
+                "after": "    let message = errorMessage ?? L10n.Global.Info.success\n"
+            ],
+            [
+                "before": "param: callFunction(errorMessage != nil ? errorMessage! : L10n.Global.Info.success),\n",
+                "after": "param: callFunction(errorMessage ?? L10n.Global.Info.success),\n"
```
Comment (Jeehut) [inline lint.swift:342]: Codacy found an issue: [Multi-line collection literals should have trailing commas.](https://app.codacy.com/gh/Flinesoft/HandySwift/pullRequest?prid=5730214)

**Comment by Jeehut** [comment]
@knothed What do you think of this? Since you implemented this in the first place, do you agree with my changes?
